#!/usr/bin/env python3
"""Generate the CMS-backed parts of the static site.

The generator intentionally has no third-party dependencies.  It understands the
small, predictable YAML subset used by Decap CMS and escapes markdown before
rendering it, so an editorial field cannot inject arbitrary HTML into the site.
"""

from __future__ import annotations

import argparse
import html
import os
import re
import sys
import unicodedata
from pathlib import Path
from tempfile import NamedTemporaryFile
from urllib.parse import urlparse


ROOT = Path(__file__).resolve().parents[1]
GENERATED_MARKER = "<!-- Generated by scripts/generate_site.py; do not edit. -->"


def scalar(value: str):
    value = value.strip()
    if not value:
        return ""
    if value[0:1] in ("'", '"') and value[-1:] == value[0]:
        return value[1:-1].replace("\\" + value[0], value[0])
    if value.lower() in ("true", "false"):
        return value.lower() == "true"
    if value.startswith("[") and value.endswith("]"):
        return [scalar(item) for item in value[1:-1].split(",") if item.strip()]
    if re.fullmatch(r"-?\d+", value):
        return int(value)
    return value


def read_yaml(path: Path) -> dict:
    """Read the flat YAML emitted by the CMS (plus simple inline lists)."""
    result = {}
    if not path.exists():
        return result
    return read_yaml_text(path.read_text(encoding="utf-8"))


def read_entry(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    data = {}
    body = text
    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) == 3:
            data = read_yaml_text(parts[1])
            body = parts[2].lstrip("\r\n")
    data["_body"] = body.strip()
    data["_file"] = path
    return data


def read_yaml_text(text: str) -> dict:
    result = {}
    lines = text.splitlines()
    index = 0
    while index < len(lines):
        line = lines[index]
        if not line.strip() or line.lstrip().startswith("#") or ":" not in line:
            index += 1
            continue
        key, value = line.split(":", 1)
        value = value.strip()
        if value.startswith(("|", ">")):
            block = []
            index += 1
            while index < len(lines) and (not lines[index].strip() or lines[index].startswith((" ", "\t"))):
                block.append(lines[index].strip())
                index += 1
            result[key.strip()] = ("\n" if value.startswith("|") else " ").join(block).strip()
            continue
        result[key.strip()] = scalar(value.split(" #", 1)[0])
        index += 1
    return result


def text(value, default="") -> str:
    return str(value if value is not None else default).strip()


def slugify(value: str, fallback: str) -> str:
    value = unicodedata.normalize("NFKD", text(value)).encode("ascii", "ignore").decode()
    value = re.sub(r"[^a-zA-Z0-9]+", "-", value.lower()).strip("-")
    return value or fallback


def safe_url(value: str, fallback="#") -> str:
    parsed = urlparse(value)
    if parsed.scheme or parsed.netloc or value.startswith("//"):
        return fallback
    return html.escape(value, quote=True)


def inline_markdown(value: str) -> str:
    """Escape first, then support the harmless inline markdown CMS authors use."""
    escaped = html.escape(value, quote=False)
    escaped = re.sub(r"`([^`]+)`", r"<code>\1</code>", escaped)
    escaped = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", escaped)
    escaped = re.sub(r"\*([^*]+)\*", r"<em>\1</em>", escaped)

    def link(match):
        label = match.group(1)
        url = match.group(2).strip()
        return '<a href="{}">{}</a>'.format(safe_url(url), label)

    return re.sub(r"\[([^\]]+)\]\(([^)]+)\)", link, escaped)


def markdown_to_html(markdown: str) -> str:
    lines = markdown.splitlines()
    output = []
    paragraph = []
    in_list = False

    def flush_paragraph():
        if paragraph:
            output.append("<p>{}</p>".format(" ".join(paragraph)))
            paragraph.clear()

    def close_list():
        nonlocal in_list
        if in_list:
            output.append("</ul>")
            in_list = False

    for raw in lines:
        line = raw.strip()
        if not line:
            flush_paragraph()
            close_list()
            continue
        heading = re.match(r"^(#{1,6})\s+(.+)$", line)
        if heading:
            flush_paragraph()
            close_list()
            level = len(heading.group(1))
            output.append("<h{}>{}</h{}>".format(level, inline_markdown(heading.group(2)), level))
            continue
        item = re.match(r"^[-*]\s+(.+)$", line)
        if item:
            flush_paragraph()
            if not in_list:
                output.append("<ul>")
                in_list = True
            output.append("<li>{}</li>".format(inline_markdown(item.group(1))))
            continue
        close_list()
        paragraph.append(inline_markdown(line))
    flush_paragraph()
    close_list()
    return "\n".join(output)


def atomic_write(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    with NamedTemporaryFile("w", encoding="utf-8", newline="\n", dir=path.parent,
                            prefix=".generate-", suffix=".tmp", delete=False) as handle:
        temporary = Path(handle.name)
        handle.write(content)
    try:
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


def replace_region(path: Path, name: str, content: str) -> bool:
    """Replace only a marked region, never the hand-authored page around it."""
    current = path.read_text(encoding="utf-8")
    begin = "<!-- BEGIN GENERATED {} -->".format(name)
    end = "<!-- END GENERATED {} -->".format(name)
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
    replacement = "{}\n{}\n{}".format(begin, content.strip(), end)
    if pattern.search(current):
        atomic_write(path, pattern.sub(replacement, current, count=1))
        return True
    return False


def entries(folder: Path):
    return [read_entry(path) for path in sorted(folder.glob("*.md"))] if folder.exists() else []


def render_news(items, identity):
    if not items:
        return '<p class="muted">Nenhuma notícia publicada ainda.</p>'
    cards = []
    for item in sorted(items, key=lambda x: text(x.get("date")), reverse=True):
        title = text(item.get("title"), "Notícia")
        summary = text(item.get("summary")) or text(item.get("_body"))
        status = text(item.get("status"), "Publicado")
        cards.append(
            '<article class="news-card">\n'
            '<span class="news-date">{}</span>\n'
            '<h2>{}</h2>\n'
            '<p>{}</p>\n'
            '<div class="news-body">{}</div>\n'
            '</article>'.format(
                html.escape(status), html.escape(title), html.escape(summary),
                markdown_to_html(text(item.get("_body"))),
            )
        )
    studio = html.escape(text(identity.get("studio_name"), "Estúdio"))
    return '<p class="generated-source">Publicações de {}.</p>\n<div class="news-grid">\n{}\n</div>'.format(
        studio, "\n".join(cards)
    )


def render_characters(items):
    if not items:
        return '<p class="muted">Nenhum personagem cadastrado no CMS ainda.</p>'
    cards = []
    for item in items:
        name = text(item.get("name"), "Personagem")
        role = text(item.get("role"))
        group = slugify(text(item.get("group"), "outros"), "outros")
        description_value = text(item.get("description"))
        description = description_value or text(item.get("_body"))
        image = text(item.get("image"))
        image_url = safe_url(image, "") if image else ""
        art = (
            '<img class="character-image" src="{}" alt="{}">'
            .format(image_url, html.escape(name, quote=True))
            if image_url else ""
        )
        extra = text(item.get("_body")) if description_value else ""
        body_html = markdown_to_html(extra) if extra else ""
        cards.append(
            '<article class="plaque" data-character-card data-character-type="{}">\n'
            '{}<h3>{}</h3><span class="role">{}</span><div class="character-description">{}</div>{}\n'
            '</article>'.format(group, art, html.escape(name), html.escape(role),
                                markdown_to_html(description), body_html)
        )
    return "<div class=\"grid-cards\">\n{}\n</div>".format("\n".join(cards))


def chapter_filename(item, used, root=ROOT):
    base = slugify(text(item.get("slug")) or text(item.get("title")), "capitulo")
    candidate = root / "herdeiros-do-gelo" / "cms-capitulos" / (base + ".html")
    while (
        str(candidate).lower() in used
        or (
            candidate.exists()
            and GENERATED_MARKER not in candidate.read_text(encoding="utf-8")
        )
    ):
        base += "-cms"
        candidate = candidate.with_name(base + ".html")
    used.add(str(candidate).lower())
    return candidate


def render_chapter(item, target: Path, identity):
    number = text(item.get("number"), "?")
    title = text(item.get("title"), "Capítulo")
    summary = text(item.get("summary"))
    studio = html.escape(text(identity.get("studio_name"), "Estúdio"))
    body = markdown_to_html(text(item.get("_body")))
    return """<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Capítulo {number} — {title}</title>
<meta name="description" content="{summary}">
<link rel="stylesheet" href="../../style.css"><link rel="icon" href="../../favicon.svg" type="image/svg+xml">
</head>
<body>
{marker}
<a class="skip-link" href="#conteudo">Pular para o conteúdo</a>
<header class="site"><div class="bar">
<a class="brand" href="../../index.html"><span class="glyph">❄</span><span><strong>{studio}</strong><small>Herdeiros do Gelo</small></span></a>
<nav class="main" aria-label="Navegação principal"><a href="../index.html">Início</a><a href="../mundo.html">Mundo</a><a href="../personagens.html">Personagens</a><a class="active" aria-current="page" href="../capitulos.html">Capítulos</a><a href="../apendices.html">Apêndices</a></nav>
</div></header>
<main class="wrap" id="conteudo"><section class="hero-chapter"><span class="eyebrow">Capítulo {number}</span><h1>{title}</h1></section>
<section class="chapter-body">{body}</section>
<div class="chapter-nav"><a href="../capitulos.html">← Voltar aos capítulos</a></div></main>
<footer class="site"><div class="wrap footer-grid"><div>© 2026 {studio} · Todos os direitos reservados.</div></div></footer>
<script src="../../reader.js"></script><script src="../../search.js"></script><script src="../../site.js"></script>
</body></html>
""".format(marker=GENERATED_MARKER, number=html.escape(number), title=html.escape(title),
           summary=html.escape(summary, quote=True), studio=studio, body=body)


def generate(root=ROOT):
    identity = read_yaml(root / "content" / "site" / "identidade.yml")
    news = entries(root / "content" / "noticias")
    characters = entries(root / "content" / "personagens")
    chapters = entries(root / "content" / "capitulos")

    news_page = root / "noticias.html"
    character_page = root / "herdeiros-do-gelo" / "personagens.html"
    chapter_page = root / "herdeiros-do-gelo" / "capitulos.html"
    missing = []
    identity_content = '<span class="generated-studio-name">{}</span><span class="generated-studio-description">{}</span>'.format(
        html.escape(text(identity.get("studio_name"), "Estúdio")),
        html.escape(text(identity.get("description"), "Universos para explorar.")),
    )
    index_page = root / "index.html"
    if not replace_region(index_page, "IDENTITY", identity_content):
        missing.append(str(index_page))
    if not replace_region(news_page, "NEWS", render_news(news, identity)):
        missing.append(str(news_page))
    if not replace_region(character_page, "CHARACTERS", render_characters(characters)):
        missing.append(str(character_page))

    used = set()
    chapter_links = []
    for item in chapters:
        target = chapter_filename(item, used, root)
        atomic_write(target, render_chapter(item, target, identity))
        label = "Capítulo {} — {}".format(text(item.get("number"), "?"), text(item.get("title"), ""))
        chapter_links.append('<a class="chapter-card" href="cms-capitulos/{}"><span class="num">{}</span><h3>{}</h3><p>{}</p></a>'.format(
            html.escape(target.name), html.escape(label.split(" — ", 1)[0]),
            html.escape(text(item.get("title"), "Capítulo")),
            html.escape(text(item.get("summary"))),
        ))
    chapter_content = (
        '<section class="volume generated-volume"><div class="volume-head"><div><span class="vnum">CMS</span>'
        '<h2>Capítulos do Decap CMS</h2></div><span class="vcount">{} capítulo(s)</span></div>'
        '<div class="chapter-grid">{}</div></section>'.format(len(chapters), "\n".join(chapter_links))
        if chapters else '<p class="muted">Nenhum capítulo novo publicado pelo CMS.</p>'
    )
    if not replace_region(chapter_page, "CHAPTERS", chapter_content):
        missing.append(str(chapter_page))
    return missing


def check_links(root=ROOT):
    errors = []
    for page in root.rglob("*.html"):
        # Asset examples in editorial comments are intentionally not real links.
        content = re.sub(r"<!--.*?-->", "", page.read_text(encoding="utf-8"), flags=re.S)
        for attribute, value in re.findall(r'\b(href|src)="([^"]+)"', content, re.I):
            if value.startswith(("#", "http://", "https://", "mailto:", "data:", "//")):
                continue
            target = (page.parent / value.split("#", 1)[0]).resolve()
            if not target.exists():
                errors.append("{}: {} -> {}".format(page.relative_to(root), attribute, value))
    return errors


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="generate and validate local links")
    args = parser.parse_args(argv)
    missing = generate()
    if missing:
        print("Regiões geradas ausentes (arquivos preservados): " + ", ".join(missing), file=sys.stderr)
        return 1
    errors = check_links() if args.check else []
    if errors:
        print("Links locais inválidos:", file=sys.stderr)
        print("\n".join(errors), file=sys.stderr)
        return 1
    print("Site gerado com segurança: notícias={}, personagens={}, capítulos={}".format(
        len(entries(ROOT / "content" / "noticias")),
        len(entries(ROOT / "content" / "personagens")),
        len(entries(ROOT / "content" / "capitulos")),
    ))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
